---
name: sparc2
version: "0.0.1"
description: "SPARC 2.x"
path:
  geodash: "./src/geodash"
less:
  pre:
    - "./src/geodash/global/sparc.less"
  paths:
    - "./src/geodash/global"
  outfile: "sparc.css"
  dest: "./build/css/"
bootstrap:
  src: "/home/vagrant/geodash-framework-django.git/geodash/static/geodash/lib/bootstrap/3.3.5/less"
  variables: "./src/less/bootstrap/variables.less"
  dest: "./build/bootstrap"
plugins:
  - sparc2
  - https://github.com/wfp-ose/sparc2-plugin-calendar.git
  #- file:///home/vagrant/sparc2-plugin-calendar.git
  - https://github.com/geodashio/geodash-plugin-map-map.git
  #- file:///home/vagrant/geodash-plugin-map-map.git
  #- map_map
  - https://github.com/wfp-ose/sparc2-plugin-sidebar.git
  #- file:///home/vagrant/sparc2-plugin-sidebar.git
  - main
  - https://github.com/wfp-ose/sparc2-plugin-welcome.git
  #- file:///home/vagrant/sparc2-plugin-welcome.git
dependencies:
  production:
    javascript:
      - "./src/js/main/*.js"
      - "./build/meta/meta.js"
      - "./build/templates/templates.js"
    templates:
      - "./src/templates/*.html"
    project:
      - "~/geodash-base.git/config.yml"
  test:
    javascript:
      - "./src/js/main/*.js"
      - "./src/js/polyfill/*.js"
compiler:
  list:
    - name: "monkeypatch_js"
      type: "js"
      src: "./src/js/monkeypatch/*.js"
      outfile: "monkeypatch.js"
      dest: "./build/js/"
    - name: polyfill_js
      type: js
      src: "./src/js/polyfill/*.js"
      outfile: "polyfill.js"
      dest:  "./build/js/"
resources:
 - name: sparc.less
   path: ./src/geodash/global/sparc.less
 - name: bootstrap.css
   path: ./build/bootstrap/bootstrap.css
 - name: polyfill.min.js
   path: ./build/js/polyfill.min.js
 - name: sparc2-core.js
   path: /home/vagrant/sparc2-core.js.git/dist/sparc2-core.js
   minified: /home/vagrant/sparc2-core.js.git/dist/sparc2-core.min.js
build:
  main.css:
    name: main.css
    type: less
    src:
      - type: resource
        project: sparc2
        name: sparc.less
      - type: variable
        name: compile_less # GeoDash will concat array variables
    outfile: sparc2.css
    dest: ./build/css
    paths: ./src/geodash/global
  monolith.css:
    name: monolith.css # more complicated, since need to automatically rewrite paths in urls
    type: css
    src: []
  polyfill.js:
    name: polyfill.js
    type: js
    src: "./src/js/polyfill/*.js"
    outfile: polyfill.js
    dest: ./build/js/
  main.js:
    name: main.js
    type: js
    uglify: true # Create an uglified version at *.min.js
    src:
      - type: variable
        name: compile_js # GeoDash will concat array variables
    outfile: sparc2.js
    dest: ./build/js/
  monkeypatch.js:
    name: monkeypatch.js
    type: js
    src: "./src/js/monkeypatch/*.js"
    outfile: monkeypath.js
    dest: ./build/js/
  monolith.js:
    name: monolith.js
    type: js
    src:
      - type: resource
        project: geodash
        version: "1.9.1"
        name: jquery.js
      - type: resource
        project: geodash
        version: "1.11.4"
        name: jquery-ui.js
      - type: resource
        project: geodash
        name: yaml.js
#      - type: resource
#        project: geodash
#        version: "4.0.1"
#        name: select2.full.js
      - type: resource
        project: geodash
        version: geodash
        name: typeahead.js
      - type: resource
        project: geodash
        version: "1.4.0-beta.4"
        names:
          - angular.js
          - angular-route.js
          - angular-sanitize.js
          - angular-cookies.js
      - type: resource
        project: geodash
        version: "3.3.5"
        name: bootstrap.js
      - type: resource
        project: geodash
        version: "3.5.14"
        name: d3.js
      - type: resource
        project: geodash
        version: "0.4.10"
        name: c3.js
      - type: resource
        project: geodash
        version: "3.17.1"
        name: ol3.js
#      - type: resource
#        project: geodash
#        version: "1.0.0-b1"
#        name: leaflet-src.js
#      - type: resource
#        project: geodash
#        name: leaflet.utfgrid-src.js
#      - type: resource
#        project: geodash
#        names:
#          - wfp-simpleheat.js
#          - wfp-heatcanvas.js
#          - wfp-heatlayer.js
#      - type: resource
#        project: geodash
#        name: leaflet.label-src.js
#      - type: resource
#        project: geodash
#        version: custom
#        name: leaflet.TileLayer.WMTS.js
      - type: resource
        project: geodash
        version: "1.3.0"
        name: showdown.js
      - type: build
        name: monkeypatch.js
      - type: resource
        project: geodash
        version: "0.0.1"
        name: geodash.js
      - type: resource
        project: sparc2
        version: "0.0.1"
        name: sparc2-core.js
      - type: build
        name: main.js
    outfile: sparc2.full.js
    dest: ./build/js/
